---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: yes

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install dependencies for this test
  - ansible-galaxy install danie1cohen.virtualenv3 -p ../
  - ansible-galaxy install danie1cohen.django -p ../
  - ansible-galaxy install danie1cohen.nginx -p ../

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # view the generated configs
  - sudo cat /etc/nginx/sites-enabled/somesite.conf
  - sudo cat /etc/init/django_demo-uwsgi.conf
  - sudo cat /opt/django_demo/django_demo_uwsgi.ini

  # show logs
  - sudo tail /var/log/nginx/error.log
  - sudo tail /var/log/upstart/django_demo-uwsgi.log
  - sudo tail /var/log/django_demo_uwsgi.log

  # check the status code response of the served page
  - "curl -v http://localhost:8888/"
  - "curl -v http://localhost:8888/ &> tmp && cat tmp | grep 200"

  # Run again to test idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_success: >
  cp MERGE.sh ~/ && chmod +x ~/MERGE.sh && ~/MERGE.sh $USERNAME $TOKEN > /dev/null 2>&1
  && (echo 'Auto-merge suceeded' && exit 0)
  || (echo 'Auto-merge failed' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
