--- # tasks/main.yml for uwsgi

- name: install uwsgi globally
  pip: name=uwsgi state=present
  become: true
  when: virtualenv is not defined

- name: install uwsgi in virtualenv
  pip: name=uwsgi state=present virtualenv={{ virtualenv }}
  when: virtualenv is defined

- name: confirm isntall path for uwsgi.ini exists
  file: path={{ uwsgi_install_path }} state=directory
  become: true

- name: create uwsgi.ini
  template: src=templates/uwsgi.ini.j2 dest={{ uwsgi_install_path }}/{{ uwsgi_project }}_uwsgi.ini
  become: true
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int <= 14
  notify:
    - restart uwsgi

- name: create upstart script
  template: src=templates/uwsgi_upstart.conf.j2 dest=/etc/init/{{ uwsgi_service_name }}.conf
  become: true
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int <= 14
  notify:
    - restart uwsgi

- name: create systemd service
  template: src=templates/systemd.service.j2
            dest=/etc/systemd/system/{{ uwsgi_service_name }}.service
  become: true
  when: ansible_os_family != "Debian" or ansible_distribution_major_version|int > 14
  notify:
    - restart uwsgi
